table:
  primitives:
    # The type and dimension definition is defined in shape_msgs/msg/SolidPrimitive
    - type: "BOX"
      dimensions: [1.0, 1.0, 0.05]
      # Pose is defined in x, y, z (meter), roll, pitch, yaw (radian)
      pose: [1.25, 0.0, 0.5, 0.0, 0.0, 0.0]
    - type: "BOX"
      dimensions: [0.05, 0.05, 0.5]
      pose: [1.7, 0.45, 0.25, 0.0, 0.0, 0.0]
    - type: "BOX"
      dimensions: [0.05, 0.05, 0.5]
      pose: [0.8, 0.45, 0.25, 0.0, 0.0, 0.0]
    - type: "BOX"
      dimensions: [0.05, 0.05, 0.5]
      pose: [1.7, -0.45, 0.25, 0.0, 0.0, 0.0]
    - type: "BOX"
      dimensions: [0.05, 0.05, 0.5]
      pose: [0.8, -0.45, 0.25, 0.0, 0.0, 0.0]
ball:
  primitives:
    - type: "SPHERE"
      dimensions: [0.05]
      pose: [1.25, 0.0, 0.6, 0.0, 0.0, 0.0]
